title = "Marshall Rosenberg Quotes - NVC Training 7 - Power of Empathy"

[NVCTraining.power-of-empathy.Q01]
key1 = '''the concept of mental illness takes the focus away from what might be causing the problems, the structures and the education they require'''

[NVCTraining.power-of-empathy.Q02]
key1 = '''Just to receive empathy for what is alive in us the pain that's alive in us that may have been stimulated years ago. But that pain is still with us right now, when we get an empathic connection with that pain, that's a very powerful contribution to healing.'''

[NVCTraining.power-of-empathy.Q03]
key1 = '''We all have this ability to learn how to listen empathically to one another, and to contribute to one another, transforming this pain.'''


[NVCTraining.power-of-empathy.Q04]
key1 = '''When we get empathy for our pain, that exists as a result of what was stimulated by others, that contributes to healing.'''

key2 = '''When we can empathically connect, with what was going on in the person who stimulated our pain, that contributes to healing.'''

[NVCTraining.power-of-empathy.Q05]
key1 = '''healing takes place, **when a person in pain both gets empathy for the pain that they're experiencing, and is able to give empathy to the person who stimulated the pain'''

key2 = '''Healing can take place if I empathically connect with people myself, playing the role of the person who stimulated the pain.'''

fbiq = '''I want to be sure I'm hearing you.'''

[NVCTraining.power-of-empathy.Q06]
key1 = '''I think we can heal from this situation, if you can tell me what's alive in you now, as a result of what happened in the past'''

key2 = '''In nonviolent communication, that what is alive in you now is what are you feeling? And what are you needing?''' 

[NVCTraining.power-of-empathy.Q07]
key1 = '''I've asked people what their needs are, but they don't tell me their needs. They're very literate telling me what they think about themselves in a way that implies there is something wrong with them. That's the kind of thinking I believe contributes to depression.'''

key2 = '''these judgments that we make of ourselves that stimulate depression are simply expressions of unmet needs'''

key3 = '''we haven't been educated to think in terms of what's alive in us, what we're feeling and needing. We've been educated to think of what we are.'''

key4 = '''if we can recognize these thoughts when we're having them and translate them into unmet needs, we live in a different world'''

[NVCTraining.power-of-empathy.Q08]
key1 = '''if you want to know how to get really depressed in life, have children and think there is such a thing as a good parent'''

key2 = '''parenting, this precious opportunity to bring people into the world and prepare them for the world, it's a precious job, but if we have been educated to think of ourself in a moralistic, judgmental way, we can take that job and turn it into something miserable'''

key3 = '''all of those judgments, that have that effect on us, are really valuable messages if we hear the truth, to hear that what they really are trying to say is, a need of mine is not getting met by what I'm doing'''

key4 = '''help people to become conscious that these judgments they're telling themselves, that create their misery, contain valuable information if we can hear the needs that are not getting met'''

[NVCTraining.power-of-empathy.Q09]
key1 = '''I predict that will resolve the conflict within 20 minutes from the point at which each party can tell me what the other party's needs are.'''

[NVCTraining.power-of-empathy.Q10]
key1 = '''What I mean by a need contains no reference to specific strategies of what we want people to do or not do.'''

[NVCTraining.power-of-empathy.Q11]
key1 = '''nonviolent communication provides us with skills for clearly expressing our needs without criticizing the other person'''

[NVCTraining.power-of-empathy.Q12]
key1 = '''all judgments and criticisms of others are tragic expressions of our needs'''

[NVCTraining.power-of-empathy.Q13]
key1 = '''it took a couple more repetitions of her need to be trusted, before he could just hear that, and keep separate his diagnoses of her.'''

[NVCTraining.power-of-empathy.Q14]
key1 = '''How amazing it is that long standing conflicts can be resolved fairly easily, when we get past the enemy images and can just get people to see the humaneness of both sides.'''

[NVCTraining.power-of-empathy.Q15]
key1 = '''I'm confident we can resolve the conflict without further violence when both sides can clearly express their needs, and be heard by the other side.'''

[NVCTraining.power-of-empathy.Q16]
key1 = '''This is where I think violence is provoked on our planet, when we educate people to think in terms of wrongness of one another, not to think a language of life, to clarify what our needs are and to hear other people's needs.'''


[NVCTraining.power-of-empathy.Q17]
key1 = '''The conflict is never at the need level. 

The conflict is in the thinking of both sides, it turns the other side into an enemy. That thinking is in terms of strategies for meeting one's own needs and not the other person's needs.'''

[NVCTraining.power-of-empathy.Q18]
key1 = '''It took about an hour just to get both sides to express a need and to hear the other side's needs. At that point, one of the chiefs who hadn't spoken yet said to me, Marshall, if we know how to communicate this way, we don't have to kill each other.'''

[NVCTraining.power-of-empathy.Q19]
key1 = '''I'm convinced we don't have to have violence if we can learn how to connect with each other's needs. 

When we're conscious that we all have the same needs, 

when we're conscious that our enemy images of one another get in the way of our connecting at the need level,

and when we see we can never win at someone else's expense.'''

short = '''I'm convinced we don't have to have violence if we can learn how to connect with each other's needs.'''

ideal = '''we all have the same human needs'''

[NVCTraining.power-of-empathy.Q20]
key1 = '''If we are skilled at nonviolent communication we can loan our nonviolent communication skills, we can loan our empathy skills by helping each side translate their criticism or judgments of the other into their needs, and then helping the other side to hear it.'''

[NVCTraining.power-of-empathy.Q21]
key1 = '''if we have the ability to empathically connect with what people's needs are behind judgmental messages they make of the other side, we can be of great support in reconciliation and creating harmony between the two sides'''

[NVCTraining.power-of-empathy.Q22]
key1 = '''Reconciliation takes the form of helping empathic connection take place by helping people to identify what their needs are, that are not being met, and how to express them without putting it in the form of criticism.'''