title = "Marshall Rosenberg Quotes - NVC Training 2 - Self Communication"

[NVCTraining.self-talk.Q01]

key1 = '''Nonviolent communication requires quite a transformation from how many of us have been programmed to communicate. 

Many of us have been programmed to communicate in a language of categorizing people and their actions to judge what they are, for doing what they're doing.'''

[NVCTraining.self-talk.Q02]

key1 = '''I thought to myself, how can I go through a day without insulting people? 

My brain had been programmed to think in terms of what people think of me.

Will they judge me right or wrong, good or bad, appropriate or inappropriate? 

And I was taught to judge others this way.'''

[NVCTraining.self-talk.Q03]

key1 = '''OJ Harvey, at the University of Colorado, took samples of literature from different cultures to see how often this verb "to be" was used in judging people's actions good, bad, right, wrong, etc. He correlated this with measures of violence - violence toward oneself, violence toward others, and he finds a high correlation. The more cultures think in terms of what people are and their actions, the more violence in those cultures.'''

key1-chunk = '''The more cultures think in terms of what people are and their actions, the more violence in those cultures.'''

[NVCTraining.self-talk.q04]

key1 = "Anger, Depression, Guilt, Shame"

key1-1 = "These four feelings are very helpful because when we feel these feelings, we can use them as an alert, that we're thinking in a way that's contributing to violence on the planet. Here is an opportunity for us to transform that thinking."

key1-2 = "Whenever we're feeling those feelings, we are thinking in a way that we have been taught to think for about 10,000 years. A way of thinking designed to make us obedient to authority, but a way of thinking that is not conducive to safety and peace on our planet."

key1-3 = "We can use those feelings as a wake up signal. Wake up, we're thinking in a way that's not conducive to peace on the planet. Let's transform the thinking into one that promotes peace on our planet"

[NVCTraining.self-talk.q05]
key1 = '''on the subject of anger, that's a good feeling to teach us nonviolent communication, because anger tells us that we are disconnected from our needs, the central part of nonviolent communication. Anger tells us we're thinking in a way that creates violence on the planet.'''

[NVCTraining.self-talk.q06]
key1 = "I tried to make clear to you that it's never what other people do that makes us angry. It's how we think that makes us angry."

[NVCTraining.self-talk.q07]
key1 = "Anger is caused by how you think, language that is disconnected from your needs, and makes violence enjoyable"

[NVCTraining.self-talk.q08]
key1 = "All you need to do to make violence enjoyable, is think there's bad guys, and that these bad guys deserve to suffer for what they've done. It can make it enjoyable for you to create pain for these people."

[NVCTraining.self-talk.q09]
key1 = "Anger tells us, in other words, that a need of ours isn't getting met. But our thinking doesn't connect with that need. Our connection goes to judging the other person who was the stimulus for the anger."

[NVCTraining.self-talk.q10]

key1 = "We can only be angry when we get disconnected from life, and go up to our head, and think in a way we have been programmed to think, in terms of wrongness of the other person."

key2 = "I'm not saying there's anything wrong with being angry. That would be unfortunate if I come across that way, because a lot of people have been educated to think that if you're a nice person, you don't get angry. They've been taught to repress their anger. I'm certainly not saying that." 

key3 = "No matter what you might say to them, do you think you are more likely to come out with your needs met, if in your head, you have judgments of them implying wrongness on their part, or if you are conscious of your needs?"

[NVCTraining.self-talk.q11]

key1 = '''This principle is very important to liberating ourselves from language which is not conducive to our well being or peace on the planet

Awareness that all language implying wrongness, criticism, insult, diagnosis of pathology of others, all such languages, are the cause of anger'''

key2 = '''All language implying wrongness, criticism, insult, diagnosis of pathology of others, all such languages, are the cause of anger.

Other people are never the cause, only the stimulus.'''

key3 = "anger is a distorted expression of an unmet need. A distorted expression that not only interferes with getting the needs met, but makes it enjoyable to be violent to others."

key4 = "Ask yourself, wait a minute, what need of mine is not getting met thats being expressed through judgment of the other person?"

key5 = "We live in a different world when we are connected to what is alive in us meeting our needs. We live in a different world than when we are up in our head, judging other people in terms of rightness and wrongness."

[NVCTraining.self-talk.q12]
key1 = "Learning how to become literate with a language of life, and our needs, is going to take some practice. We're going to need to practice transforming language which stimulates violence into a language of life." 

[NVCTraining.self-talk.q13]
key1 = "Out beyond ideas of wrongdoing and rightdoing, there is a field. I’ll meet you there.\" - Rumi"

[NVCTraining.self-talk.q14]
key1 = "I was very skilled at judging what's wrong with other people in a way that would make me angry. But I wasn't very skilled at understanding my needs, getting connected to my needs."


[NVCTraining.self-talk.q15]
key1 = "It would sometimes be awkward when I was angry, because I would stop right there at that time, take a deep breath, identify the thinking making me angry, connect to the need behind it, and then I would open my mouth."

[NVCTraining.self-talk.q16]
key1 = '''He said, Dad, it's taking you so long to talk. I said, let me tell you what I can say quickly, do it my way or I'll kick your butt. He said, Take your time, dad. 

People who have known me in the days before I learned nonviolent communication are very patient when I take my time.'''

[NVCTraining.self-talk.q17]
key1 = '''One way in which we can make our own life much more enjoyable, is whenever we are thinking in a way that is causing anger, depression, guilt, or shame, to transform that thinking into what need of ours is being distorted by the thinking that's causing those feelings.'''

key2= '''In the exercise where I have asked people to identify what they tell themselves when they have made a mistake. Once they identify this thinking, I then suggest that they transform that thinking into the need that wasn't met, that stimulated the thinking.'''

key3 = '''In other words, I tell them that all of the thinking that makes us angry, depressed, guilt or shame is a tragic expression of an unmet need. To really learn from this mistake, without losing self respect, we need to mourn but to mourn without blaming.'''

key4 = '''This is a very important difference in nonviolent communication, the difference between morning and blaming ourselves. Morning requires that we be connected to our need that wasn't met by our behavior. When we're connected to that, we might feel sadness, frustration. These are quite different feelings in terms of their effect on our spirit and on our bodies, than how we feel when we blame ourselves and feel the depression, guilt, shame.'''

key4-b = '''Morning requires that we be connected to our need that wasn't met by our behavior. When we're connected to that, we might feel sadness, frustration. These are quite different feelings in terms of their effect on our spirit and on our bodies, than how we feel when we blame ourselves and feel the depression, guilt, shame.'''

key5 = '''We suggest that everyone build at least a vocabulary of about nine words that describe various needs that you have and at see if one of those words, or more, resonate when you're blaming yourself.
'''

key6 = '''The quicker we can transform a thinking of blame into a thinking of unmet needs, the quicker we're going to be able to learn from our mistakes without losing self-respect.

This kind of self empathy, empathizing with the need being expressed behind self blame, we call that morning.'''

key7 = '''First, be conscious of what you tell yourself as a result of making the mistake, and translate the self-judgment, into an unmet need. That's morning.

Then empathize with what need you were trying to meet by the action that we're calling a mistake. That's self forgiveness.'''

[NVCTraining.self-talk.q18]
key1 = "In my clinical training, I was taught to look at depression as an illness as a mental illness. I now come to see it in quite a different way. [...] I find that depression is created by people judging themselves in a way that creates that depression."

key2 = "When I'm seeing somebody who's very depressed, I ask, what needs of yours are not being met? They very seldom are able to tell me that. They haven't been educated to be conscious of their needs. They've been educated to blame themselves and others."

key3 = '''I ask, What needs of yours aren't being met?

They say, \"I'm a failure.\"

I asked about needs, they tell me a judgment of themselves. 

I point out this difference:

\"You're telling me now what you think of yourself. I'm asking what need of yours is not being met.\'''

key4 = '''I try to show people it's this kind of thinking that makes us depressed. 

What we tell ourselves about ourselves. We judge ourself in a way we've been trained to judge people. 

These judgments that imply badness, wrongness, inferiority, abnormality, that creates the depression.'''

key5 = '''Once people have identified these judgments that create their depression, I show them how to transform the judgments into unmet needs. 

What a different world we live in when we get connected to the need that isn't getting met, rather than get stuck in the ways that we judge ourselves.'''

key6 = '''When we think in the static language of what's wrong with us, that are we selfish, stupid, inconsiderate. 

When we have that language going on in us about ourselves, that doesn't lead to us geting our needs met.

Our needs are buried behind that kind of thinking.'''

[NVCTraining.self-talk.q19]

key1 = '''The structures we have been living under for a long time require people to be nice dead people.

They teach this language of blame, so that we'er forever looking to authorities to see whether we're getting the right answer or the wrong answer, whether we're judged as good or bad.'''

[NVCTraining.self-talk.q20]
key1 = '''One of my favorite plays was written by Herb Gardner called A Thousand Clowns.

In one part of that play, two people from the educational authorities come to the hero's house. He kept his nephew, age 12, at home and not going to school. The school authorities are questioning him about why he is not sending his nephew to school.

He answers this way, "I just want him to stay with me till I can be sure he won't turn into another carbon copy of that ever popular modern hero, Norman Nothing. I want to be sure he'll know when he's chickening out on himself. I want him to stay awake, and to know who the phoneys are. I want him to know how to holler and put up an argument. I want to be sure he sees all the wild possibilities. I want him to know it's worth all the trouble just to give the world a little goosing, when you get the chance, and I want him to know the subtle, sneaky important reason why he was born a human being and not a chair.

http://www.oocities.org/hollywood/set/7601/clowns.htm
"'''

[NVCTraining.self-talk.q21]
key1 = '''When we feel pleasurefull feelings, we know that our needs are being fulfilled. When we feel painful feelings, or unpleasant feelings, we know our needs are not being fulfilled.

To be fully alive requires a language of life. That requires a language of feelings and needs.'''

key2 = '''Another thing we need to liberate ourselves from if we want to really enjoy being human, we need to liberate ourselves from thinking that we cause other people's feelings.'''

key3 = """We need to be real clear about this important word, responsibility. We need to see what we can be responsible for, and what we are not responsible for. When we get this mixed up, we can be victimized by guilt tripping."""

key4 = '''Other people can't make us feel anything. Our feelings are a result of how we take things. We cannot make other people feel as they do. They are responsible for how they take it.

We show we're not responsible for how other people feel. We are responsible for our actions.'''

[NVCTraining.self-talk.q22]
key1 = '''Very often when people see they're thinking in that way that creates feeling of shame and guilt, they say to themselves: "I shouldn't feel that way, what's wrong with me? I've been studying nonviolent communication long enough that I should no longer think that way." They judge themselves for judging themselves, which just makes them feel worse than ever.'''

key2 = '''When learning nonviolent communication, it's very important to keep conscious at all times:

The goal of life isn't to be perfect. It's to become progressively less stupid.

Let's learn from our limitations.

Let's learn from our errors, and see them as opportunities to develop ourselves.

Keep in mind that anything that's worth doing is worth doing poorly.'''

key2-b = '''The goal of life isn't to be perfect. It's to become progressively less stupid.

Let's learn from our limitations.

Let's learn from our errors, and see them as opportunities to develop ourselves.

Keep in mind that anything that's worth doing is worth doing poorly.'''

key3 = '''We didn't judge students as bad, but we spoke honestly with them about whether or not their behavior was in harmony with our values or needs. We judge that way, but not judgments of a moralistic sort that implied wrongness.

I wasn't surprised that this might upset some of the school administrators since this way of looking at the world is quite different than how many people have been educated.'''

key3-b = '''We didn't judge students as bad, but we spoke honestly with them about whether or not their behavior was in harmony with our values or needs. We judge that way, but not judgments of a moralistic sort that implied wrongness.'''

key4 ='''I was also in favor of rules, but that I showed him a different way of establishing rules based on the protective use of force and not the punitive use of force

https://nvcnextgen.org/2018/10/on-the-punishment-and-the-protective-use-of-force-by-jim-manske/'''

[NVCTraining.self-talk.q23]
key1 = '''how concerned I am about thinking we have to be afraid of what other people might say or think about us.

By doing that, we're giving our power to other people.

I tryed to show people that we need to be concerned with how we respond the other person, not what they think of us.'''

key2 = '''That's where our safety is, in how we learn to respond to other people's judgments or criticism of us. Not to give our power away by thinking that our safety is solely how they might respond.'''

key3 = '''Our safety is in how we respond to other people, not in how they respond to us.

We have all these choices when people say things to us:

- we can take it personally and feel shame
- we can judge them and feel angry
- or how we can empathically connect with them'''

key4 = "Don't ever give up your security, to the structures in which you're in, or to other people's messages toward you."

key5 = "never give the structure, or the people in it, the power to make you submit or rebel"

key6 = '''Help our children to learn how to come from their own spirituality, how to answer for themselves, "what is the way that I choose to live?" and learn how to sustain that, staying conscious of it regardless of the structures you're in, or how people in those structures speak to you'''

key7 = '''No matter what structures we're in, never give the structure or its rules the power to determine what we do. So our actions come from choosing to act in harmony with our values.

This way, we're not submitting or rebelling. We're acting in harmony with our own values each moment.'''

key8 = '''
Walter Wink, the theologian, says it's very important to be conscious, that institutions have their own spirituality. Many structures are set up in a way that are designed to get people to obey authority no matter what the authority wants them to do.

https://www.opendemocracy.net/en/transformation/transforming-powers-continuing-relevance-of-walter-wink/'''
