title = '''Marshall Rosenberg Quotes - NVC Training 5 - Relationships'''

[NVCTraining.relationships.Q01]
key1 = '''This question is very important, "do you love me?" And it's very hard to answer because we very often don't get clear in intimate relationships what we really mean by that word love.'''

key2 = '''Some people use the word love as a feeling and emotion. If they do that, it's pretty hard to know how to answer that question without reference to a specific time and place because feelings change every few seconds.'''

key3 = '''In nonviolent communication, we use the word love as a need, and a very important need. 

What's very important is to know how to manifest this need, to contribute to that need being met, in people that we care for, and that we have intimate relationships with.'''

key4 = '''When we have that ability to share that which is not easy to express, we get a chance to get these needs fulfilled. But if we are so frightened of expressing these needs that we don't say anything that creates barriers in the relationship.'''

[NVCTraining.relationships.Q02]
key1 = '''I go to my partner, and I say, I know you've got a lot of things planned today, and I talked about this day being your time to do these things. But I just got an appointment with the doctor that I need to do. I know it's not necessary for me to do it. I know I could postpone it for another day... 

The more I go on with this kind of apology for having the need and justifying it, the harder it is for the other person to give out of loving energy.'''

key2 = '''The more I go on with this kind of apology for having the need and justifying it, the harder it is for the other person to give out of loving energy'''

[NVCTraining.relationships.Q03]
key1 = '''It's very important is to develop a consciousness that our needs are precious gift if they are expressed in a way in which we are not demanding that the person meet our request, in relationship to our needs.'''

key2 = '''If the other person trusts that when we say our needs, and we follow it with a request, that we only want them to do it, if they can do it willingly, joyfully.

When we have this consciousness that our needs are a gift, we then express them with a totally different energy'''

key3 = '''When we have this consciousness that our needs are a gift, we then express them with a totally different energy that makes it much easier for the other person to enjoy receiving our needs, and makes it much easier for them to respond out of the joy of giving.'''

key4 = '''Follow the need that isn't being met with a clear request. 

If we simply express the need without the request, it often leaves the other person in a position either of not being clear what we want, or with the idea that we expect them to know what we want them to do about it.'''

[NVCTraining.relationships.Q04]
key1 = '''When I tricked myself into thinking I'm responsible for my partner's happiness, I'm taking on a job that I can't do. I can't make the other person happy.'''

key2 = '''I can only be responsible for my own actions, my own intentions. The other person is responsible for how they take what I do, how they interpret it, and what they do to get their needs met.'''

key3 = '''It's very important to see that we cannot be responsible for other people's happiness. We cannot be responsible for other people's actions. We are responsible for our own intentions and actions.'''

[NVCTraining.relationships.Q05]
key1 = '''If somebody says 'no' to us, that can't make us feel bad, it's how we interpret the no. We lose this consciousness as we get educated so that interdependence is not what happens in intimate relationships, but co-dependence, where people take on responsibility for each other's happiness.''' 

[NVCTraining.relationships.Q06]
key1 ="many of the women I work with have a difficult time expressing their needs. They have internalized cultural programming that says that loving women have no needs. Ao demonstrate their love for others, they believe that you must suppress your needs in favor of the other person."

key2 = '''Men on the other hand seemed to have real difficulty expressing their feelings, especially any feelings that imply vulnerability, like feeling hurt, or sad, or lonely. They are educated in what I call the john wayne concept of masculinity and that's supposed to have such vulnerable feelings.'''

[NVCTraining.relationships.Q07]
key1 = '''Well, the first step in saying no, is to make empathic connection with the other person's needs. 

The empathic connection lets the other person know that we do care about their needs. We show that care by taking the time to stop and really connect with what's going on in them.'''

key2 = '''We start with this empathy for the other person's needs when we say no, and then we follow it with the need of ours that keeps us from willingly being able to do what they're asking of us at this moment.'''

key3 = '''To say no:

- We empathically connect with the other person's needs, silently or verbally.
- We say our need that keeps us from saying yes.
- We end on a request that searches for a way to get everybody's needs met.'''

[NVCTraining.relationships.Q08]
key1 = '''one way, a person often says no, when they hear a demand, is no. You can tell from the tone of their voice that they heard a demand, they heard pressure upon them.'''

key2 = '''Another way that some people handle the requests they don't want to respond to. They make a diagnosis of what is wrong with the person for having the need. 

If we're going to be good at expressing our needs, we want to be sure that we are prepared to deal with somebody who gives us a diagnosis for having our needs.'''

[NVCTraining.relationships.Q09]
key1 = '''How can I let you know what my needs are, and what I'm requesting of you, so that you can believe that I only want you to do it if you can do it joyfully, that it's not giving in or giving up?'''

key2 = '''This is very important to work out in intimate relationships, how each party can hear each other's needs when they are expressed in a way that they trust that the partner only wants them to give if it can be done willing. '''

[NVCTraining.relationships.Q10]
key1 = '''Another problem that often makes it hard for people to enjoy giving in an intimate relationship is when their partner skips the need and just expresses their pain and goes immediately to a strategy.'''

key2 = '''For example, if a person says to their partner, I'm feeling very hurt. You've only been home two days out of the last month, in the evening, would you please correct your schedule so that you are home at least four evenings a week.'''

key3 = '''When they hear the pain, and immediately the pain is followed by a request. Very often in my experience, that request is going to be heard as a demand.'''

key4 = '''It's very important when we are in a good deal of pain about something, that we be conscious, it's by really focusing on our need, making the need clear and our feelings clear.'''

key5 = '''It's very important when we are in a good deal of pain about something, that we be conscious, it's by making the need clear and our feelings clear, when people have that focus, then specific strategies that are requested have a whole different case to them.'''

[NVCTraining.relationships.Q11]
key1 = '''One of the things that people in relationships find most difficult to talk about is their sexuality, and to make it clear whether their needs relative to sex are being met. 

One of the things that we recommend is that they get so good at expressing these scary messages, that they don't wait to express them when they are sitting down and have time to express. They learn to express these scary messages, even while they're having sex.'''

key2 = '''we often do a little exercise on what this would look like, how you would express, in the middle of the sexual act, when your needs are not getting met. How you could do this in a way that would be a gift to the other person?'''

[NVCTraining.relationships.Q12]
key1 = '''it may go against the cultural programming, that if you're really competent man and woman, you don't have any problems in your sexual relationships, they just flow.

The reality is, the degree to which you can be honest about such sensitive issues, even in the middle of the sexual act, I predict this is one of the best ways to enjoy sexuality more and more.'''

[NVCTraining.relationships.Q13]
key1 = '''We've got to be prepared, anytime we express ourselves vulnerably, we got to be prepared to empathically deal with what comes back.'''

[NVCTraining.relationships.Q14]
key1 = '''one way that people define intimacy, that if you really care for people in an intimate relationship, and you see what their needs are, you suppress your own needs and give to them.

My experience is that if we give, anytime, out of an energy where we feel even slightly we have given in or given up our own self, both people pay for it.'''

[NVCTraining.relationships.Q15]
key1 = '''Nonviolent communication suggests we really make sure that everything we're doing is done willingly, out of an energy that comes when we are enriching life, and it's meeting our need to enrich life, so that we never feel as though we are sacrificing ourself for the other people.'''

[NVCTraining.relationships.Q16]
key1 = '''many of the women that I work with find it very hard to hear their partner's needs without losing their own needs, other people's needs are more important to them.'''

key2 = '''There's a different energy, when we are giving fully out of our own need to contribute to the other person's well being, that isn't mixed at all, with this idea that it's our obligation or duty to care for the other person.'''

[NVCTraining.relationships.Q17]
key1 = '''Many of the men that I work with [believe] that as a man, they are totally responsible for their woman's smile and happiness so that if she's not smiling and happy, it means they have failed somehow as a man.''' 

key2 = '''Especially if the woman is not satisfied, totally, sexually, many men take it as a sign of their own inadequacy, rather than just empathically connecting with the woman to find out how the womans needs could be better met.''' 

[NVCTraining.relationships.Q18]
key1 = '''When we take responsibility for other people's feelings, rather than our own actions, that is when our giving is mixed. It doesn't contain the pure joy of giving that's necessary for relationships to be strengthened.'''