title = "Marshall Rosenberg Quotes - NVC Training 3 - Observations, Feelings, Needs, Requests"

[NVCTraining.model.Q01]
key1 = '''We're interested, in nonviolent communication, with the kind of honesty that supports people connecting with each other in a way that makes compassionate giving inevitable, that makes it enjoyable for people to contribute to each other's well being.'''

key2 = '''Many of us have been educated by an honesty that evolves from our system of justice, retributive justice which judges people as right or wrong, good or bad, with attachment to, that if you are good, right, appropriate, etc, you deserve to be rewarded, but if you are bad, wrong, etc. You deserve to suffer, be punished, etc.

It's my belief that that kind of thinking is the basis of violence on our planet. It's a way of thinking that makes violence enjoyable.'''

[NVCTraining.model.Q02]
key1 = '''We're interested, in nonviolent communication, with the kind of honesty that supports people connecting with each other in a way that makes compassionate giving inevitable, that makes it enjoyable for people to contribute to each other's well being.'''

key2 = '''This kind of honesty basically involves telling people what's alive in us, without using any words that criticize, and tell people what would make life more wonderful for us, what we are requesting, without presenting this as a demand, but presented as a request.'''

key3 = "It's very important to be able to made clear observations to people, that tell them what language on their part is stimulating our needs being fulfilled, and what things that are doing that are not fulfilling our needs."

key4 = "We can learn by clear observations, but when the observations and evaluations are mixed together, so that it sounds like a criticism, it makes the evaluation period painful for both sides."

[NVCTraining.model.Q03]
key1 = "In nonviolent communication, we want to be sure that whenever we want to talk to somebody about something they're doing that we're not happy with, that we clearly put this in the form of an observation."

key2 = """Our evaluation needs to be focused on the life within ourselves, which to me means it needs to contain reference to our needs. 

We need to let people know what needs of ours are being met or not being met by their behavior, and how we feel as a result of it."""

key3 = "When we tell people clearly our feelings and needs, we're letting them know what's alive in us when they do what they are doing, this is an evaluation based on life, not an evaluation, criticizes or blames."

[NVCTraining.model.Q04]
key1 = "This form of evaluation requires a literacy of feelings, that we tell people how we feel when they behave in a certain way."

key2 = "many people use the word feeling and thought interchangeably. In nonviolent communication, when we use the word feeling, we want it to refer to an emotion that a person is experiencing, that doesn't contain any diagnosis or intellectual analysis of the other person"

key3 = """Feelings would be,

I feel frustration,
I feel sadness,
I feel irritation, when our needs are not getting met.

When our needs are getting met,
I feel happy.
I feel joyful.
I feel pleasure."""

key4 = "We have been living under [...] domination cultures in which some people claim to be superiors and have a right to control others. People do not make good slaves when they are connected to life. Feelings are not regarded as a positive thing to say."

key5 = "Not only aren't we educated to speak a language of life, a language of feelings, we have been given a cultural education that has a very negative connotation to many of our emotions."

key6 = "We learn very quickly in life to cover up our emotions and hide them. Even though if we want to relate in a way that promotes compassion between ourselves and other people, feelings are a key ingredient."

key7 = "Painful feelings tell us our needs are not getting met. Pleasure feelings tell us our needs are being met."

key8 = "this requires a need consciousness, and a need literacy, which is not easy to come about. Because, once again, the structures in which we have been living for a long time, require us to be educated in a way, in which, we are not connected to our needs."

key9 = "Many women tell me what difficulty they have, expressing their needs. They have been taught that loving women have no needs, they sacrifice their needs for their families."

key10 = "Men tell me how difficult it is to express their needs. How they have been taught that brave men have no needs, so they're willing to sacrifice their lives for the king or for the flag."

[NVCTraining.model.Q05]
key1 = "In our training, we suggest to be sure that you learn how to be honest without any criticism without any blame, without any judgment of a kind where people hear that what they're doing is bad or wrong."

key2 = "When I say this, many people get very confused and upset with it. Their whole lives have been based on the language of good, bad, right, wrong. They see it's all about how you are judged by authority. If you're judged, right, you get rewarded, and bad, you get punished."

[NVCTraining.model.Q06]
key1 = "I was not suggesting that we not judge or evaluate people's behavior. I was suggesting that we not judge them in a way that perpetuates retributive justice, based on the concept of punishment and reward."

[NVCTraining.model.Q07]
key1 = """We suggest that everyone have at least a vocabulary of nine human needs. I picked the number nine after reading a research done by Manfred Max neef, an economist from Chile. His whole system of economics is based on human needs.

https://www.rainforestinfo.org.au/background/maxneef.htm"""

key2 = """In the United States, we measure the success of the measurements of the GNP, the gross national product, which essentially is how much money is made in certain areas.

That system shows that it's successful when the rich get richer and the poor get poorer."""

key3 = """Manfred Max-Neef approach to economic success is based on whether human needs are met by all of the parties in the culture.

Since his whole system of economy is based on human needs, he's gone to some trouble to research what are the basic human needs that need to be fulfilled, if we're to have a safe, healthy, peaceful world."""

key4 = """Max-Neef classifies the fundamental human needs as: subsistence, protection, affection, understanding, participation, recreation (in the sense of leisure, time to reflect, or idleness), creation, identity and freedom."""

key5 = """Needs are also defined according to the existential categories of being, having, doing and interacting, and from these dimensions, a 36 cell matrix is developed which can be filled with examples of satisfiers for those needs.

https://medium.com/@cathrans/draft-theories-of-change-e8d72234a5bf"""

[NVCTraining.model.Q08]
key1 = """Anytime we find ourselves wanting to criticize, when we translate that criticism into our needs that isn't being met, we are far more likely to get our needs met, when we speak our needs than when we tell people what's wrong with them."""

[NVCTraining.model.Q09]
key1 = "After we have made clear expressions of what's alive in us, namely what we're observing, what we're feeling, what we're needing, if our need is not getting met, then we need to end on a clear request."

[NVCTraining.model.Q10]
key1 = "In nonviolent communication, we tell people what we do want, rather than what we don't want."

[NVCTraining.model.Q11]
key1 = "In nonviolent communication when we've expressed a need that isn't met, we end on a clear request of what we want back at this moment. The request needs to be an action language."

[NVCTraining.model.Q12]
key1 = "if people hear demands, it takes much of the joy away from doing anything. It's much more likely to provoke resistance, than cooperation."

[NVCTraining.model.Q13]
key1 = "With many people, this is very hard to get them to trust that our requests are requests and not demands to whatever degree people carry memories, that when they don't do what other people want. They have been criticized guilted blamed punished."

[NVCTraining.model.Q14]
key1 = "In nonviolent communication, we say what is alive in us, what we're observing, feeling, and needing. We make clear requests presented, as best we can, in a way that people can trust it is a request and not a demand."

[NVCTraining.model.Q15]
key1 = "When somebody requests something of you, to say no in nonviolent communication, we begin by showing that we receive the other person's request as a gift."

key2 = '''be aware that "no" is a poor expression of a need. Anytime a person says no, they're basically saying I have a need that keeps me from wanting to do what you have requested at this moment'''

key3 = "To say no in a nonviolent communication way. We say the need that keeps us from saying yes."

key4 = "When saying no in a nonviolent communication way, is to end on a request that searches for a way to get everybody's needs met."

key5 = '''The three parts of saying no in a nonviolent communication way:

First, show an empathic reception of the request of the other person. They feel understood that their need was understood their request was understood.

Second, we don't say "no", we don't say "I can't", we say the need that keeps us from saying yes.

we end with a request that searches for a way to get everybody's needs met.'''

key6 = "One reason I've found that people use more words than anybody wants to hear is that the speaker is not conscious of what they want back. They don't understand what their own present request is, and so they keep going on and on trying to get what they want, when they're not even too sure what they want in the conversation."

key7 = "My prediction is, the more conscious you are what you want back in the form of what you're requesting of your listener, you use fewer words and get more understanding."

[NVCTraining.model.Q16]
key1 = '''The father said to me, "OK, Marshall, I think I'm seeing what you're trying to help us to see.

I said, What's that?

I see now what I want him to do, to meet my need for respect.

I said, What's that?

I want him to jump when I say jump, and smile because he feels like jumping.'''

key2 = "the father could see that when he said, I want you to respect me, he really wanted obedience. He could see, then, why the son reacted so negatively when he would ask for things."

[NVCTraining.model.Q17]

key1 = "Research shows that different people have quite different requests to get their need for love met. What will meet one person's need for love doesn't necessarily meet another's need for love."

key2 = '''She said, Okay, Marshall, I got your point. I see what's going on. I see why I'm not getting my need for love met.

Why is that? What do you want him to do to meet your need for love?

I want him to guess what I want before I know what it is, and I want him always to do it'''

key3 = '''Many of us carry around very destructive strategies for getting our basic needs met. 

Strategies that are destructive, first of all, because they're not possible, or secondly because they deny the needs of the other person, and require the other person be subservient to us.'''

key4 = "Some people use the word love as a feeling. Nonviolent communication suggests that we use the word love solely as a need and not as a feeling. If we're trying to express emotions, then use other words beside love for describing what we are feeling."


[NVCTraining.model.Q18]
key1 = "Another thing that's very important and expressing our needs in a nonviolent communication way is not to get our needs confused with strategies for getting the needs met."

key2 = '''Needs are universal. All human beings have the same needs.

The second thing that differentiates a need from a strategy, a need contains no reference to specific actions. Anytime we say "I want you to" that's not an need, that's a request or a strategy.'''

[NVCTraining.model.Q19]
key1 = "Another thing that's very important when we do express clear request, is to make sure that we are not addicted to getting what we want."

key2 = '''If your intent is to get people to do what you want, that's a different intent than we need to have.

In nonviolent communication, it's never our objective to get what we want. It's to create the quality of connection with people that ends with everybody getting their needs met.'''

key3 = '''Everyone's needs getting met, is the objective of nonviolent communication.

This doesn't require ever giving up or giving in, it just means not getting addicted to our strategy. If we're addicted to our strategy, it's very easy for the other person to hear a request as a demand, this threatens their need for autonomy, and makes it harder for them to enjoy giving.'''

key4 = '''We need to say clearly what we want. But the objective is to create a connection and then which everybody's needs get met through compassionate giving.'''


[NVCTraining.model.Q20]
key1 = '''State the observations that are leading you to feel the need to say something. These should be purely factual observations, with no component of judgment or evaluation.'''

key2 = """State the feeling that the observation is triggering in you. Or, guess what the other person is feeling, and ask. Naming the emotion, without moral judgment, enables you to connect in a spirit of mutual respect and cooperation.""" 

key3 = """State the need that is the cause of that feeling, or guess the need that caused the feeling in the other person, and ask.

Tuning into the feeling, you can often find the underlying need. Stating the need, without morally judging, gives you both clarity about what is alive in you or the other person in that moment."""

key4 = "Make a concrete request for action to meet the need just identified. Ask clearly and specifically for what you want right now, rather than hinting or stating only what you don't want."

