title = "Marshall Rosenberg Quotes - NVC Training 1 - Intro"

[NVCTraining.intro.Q01]

key1 = "\"I don't like that title [nonviolent communication]. But why do I use it? I use it because, over the years, it connects me with the people around the world that find our training very valuable in their lives, and in their political activities.\""

key2 = "\"Why don't I like the title? One of the reasons is the same reason that Gandhi didn't like the word nonviolent. It says what something isn't, but nonviolent communication is all focused on what we do want, not just what we don't want.\""

[NVCTraining.intro.Q02]

key = "Nonviolent communication consists of a value system that we are trying to live by. It outlines a language, thinking, communication skills, and means of influence that support that way of living."

[NVCTraining.intro.Q03]

key1 = """Two questions were in me:

what happens to people to lead them to enjoy, and want to contribute to other people's suffering?

What happens to human beings so that we stay with the process of compassion where we enjoy contributing to each other well being?"""

key2 = """I wanted to learn what contributes to violence, and do whatever I could to transform it, to prevent it. 

To learn about what helps human beings to stay connected to our compassionate nature, to do whatever I could to live that way myself and distribute what I learned to others."""

[NVCTraining.intro.Q04]

key1 = """While getting my doctor's degree in psychology, a professor helped me to see that clinical psychology had some limits.

He showed me that psychiatric diagnoses didn't have a basis in scientific research.

He also showed me that looking at violence as an illness takes the focus away education that structures of society provide which create violence."""
key1-length = 350

key2 = """I found that the tools of psychoanalytic therapy, and other trainings which were current at the time, didn't work very well. 

Instead of diagnosing what it was in people that's wrong with them, I decided to start with a different question: How were we meant to live?"""

key3 = """I saw that the skills that seem necessary to live compassionately are quite different than the skills that we were taught.

The structures we are living in, where some claim to be superior and know what's right for others, requires a certain way of thinking, a certain language, and a certain use of power.

I saw that was the problem. What creates violence is that way of thinking, language, and use of power."""
key3-length = 410

key4 = """I decided to a different kind of research to observe the people I respected the most, who seemed the most compassionate, who seemed to enjoy giving to others. 

I tried to see how were they different than the people who seemed to enjoy criticizing, blaming, and attacking others.

It was through studying these people, and also some research in psychology, that tried to identify what characteristics of development contribute to people's behaving in a compassionate way.

I put together from these sources a process that seemed to me to summarize how we were meant to live and the skills that were necessary to do this. 

That's how nonviolent communication evolved from the research that I did, to identify what kind of human development is necessary for us to live compassionately."""
key5-length = 784

[NVCTraining.intro.Q05]

key1 = "The process that I call nonviolent communication consists of an intention to contribute to our own well being, and the well being of others, compassionately."

key2 = "What I mean by compassionate giving is, first of all, whatever we do is done willingly, not done out of guilt, or shame, or fear of punishment, or trying to buy love by submitting to what we think others expect us to do."

key3 = "I saw that the intention I wanted to live by, that I thought necessary for compassionate giving, is that we give solely out of the joy that comes naturally from contributing to life. Our own life and the lives of others."

key4 = "I organized what I was learning about this into the program called nonviolent communication."

key5 = """In my private practice, people came to me with depression. Children were sent to me because of problems in school. Couples came to me with marital problems.

I found the process I was putting together much more effective as a healing tool than how I was taught to do psychotherapy"""

key6 = "It seemed too simple to just show them how some different ways of behaving, different ways of thinking, communicating, using power, how quickly this could correct problems that were taking me months and not getting the same result."

key7 = "I was seeing more and more how that very concept of mental illness was a destructive concept because it implied something was wrong with people that needed fixing."

[NVCTraining.intro.Q06]

key1 = """The purpose of nonviolent communication:

to provide us with the language with the thinking, communication means of influence that support and connecting with ourselves and others in a way that promotes compassionate giving."""

[NVCTraining.intro.Q07]

key1 = "For about 10,000 years over most of our planet, people have been operating according to what I call domination structures in which some people claim to be superiors and have the right to control others because they know what's best."

key2 = """How do you educate people to be submissive and obedient? 

You need to teach them a language in which they get disconnected from their own power and look to authority to guide how they ought to live."""

key3 = """To maintain domination structures, a core component is to educate people with a static language that uses the verb to be in ways that judge people, their behavior, their appearance, their intelligence.

In addition to this language that I call a language of domination, it's also important to teach people retributive justice.

Retributive justice basically implies that if you are judged as bad by the authorities, you deserve to suffer for it. If you are judged by authorities as good, then you deserve to be rewarded."""

key4 = """It's my belief that this combination of teaching people To think in a static way, in terms of good, bad, right wrong, normal, abnormal, appropriate, inappropriate, mentally normal mentally ill. 

That way of thinking combined with retributive justice, based on punishment and reward, I believe is at the heart of violence on our planet."""

[NVCTraining.intro.Q08]

key1 = """Nonviolent communication offers us a different language than a language that implies whether people deserve to be punished or reward. 

Nonviolent communication focuses our attention on human needs, whether human needs are being fulfilled or not. When they're not, obviously what is called for, is to find ways we can behave that nurture these needs. This is radically different way of thinking."""
key1-length = 395

key2 = """Instead of judging right or wrong, to determine whether people are punished or not, are rewarded or not nonviolent communication focuses on what is happening to our needs."""

key3 = """If our needs are not being fulfilled by what is happening, let us take action that fulfills our needs. If our needs are being fulfilled, let's celebrate.

This is a radical departure from the language of domination, a language of judging what people are."""

[NVCTraining.intro.Q09]
key1 = """Nonviolent communication suggest clarity about whether actions are supporting needs being fulfilled.

Nonviolent communication suggest we make clear observations that we can tell people, when their actions are meeting our needs, and when their actions are not meeting our needs."""

[NVCTraining.intro.Q10]
key1 = "Feelings are manifestations of what is happening to our needs. When our needs are not being fulfilled. We feel unpleasant feelings. When our needs are being met. We feel pleasureful feelings."

key2 = "When we see that our needs are not being fulfilled, we need to request of ourselves or others, what actions we would like taken to better meet our needs."

[NVCTraining.intro.Q11]

key1 = """Four components makeup nonviolent communication

The most basic, our needs, and then observations of what is fulfilling our needs and what isn't. Feelings to identify the results of what's happening to our needs now, whether they're being met or not. Our feelings reveal that to us. A request what we would like done about our needs that are not being fulfilled."""

key2 = """These four components basically answer two questions.

What's alive in us? When we say what is contributing to our well being, how we feel and what our needs are that are behind our feelings, that answers the question of what's alive in us at a given moment.

a second question that nonviolent communication directs itself to is what would make life more wonderful? that's where our requests come in. We say what we would like to make life more wonderful."""
key2-length = 455

key3 = "Nonviolent communication involves sharing what's alive in us. What would make life more wonderful? to receive the same information from other people, to connect with what's alive in them, and what would make life more wonderful for them." 

[NVCTraining.intro.Q12]
key1 = """I've found that anytime people hear criticism or demands, that makes it very difficult for people to enjoy contributing to one another's well being."""

key2 = "We want people to know that we never want anything done that we request out of guilt or shame created by criticism they hear coming from us."

key3 = """I believe that anytime we influence people, like criticism, blame insults, even if they do what we request, it will be very costly to us. 

They're not giving compassionately from the heart. They're giving to avoid shame or guilt. 

Giving done out of that energy, I believe, is costly to both parties in any relationship."""
key4 = 322

key6 = """Nonviolent communication suggests that we avoid at all times any use of punishment.

That shocks many people around the world that I work with, they have the idea that without punishment, you have anarchy. 

They believe that the only way you can have order is through a justice system in which people punished if they don't do what the authorities think is right."""

key7 = """We can resolve conflicts without any kind of punishment. That's not easy for many people to feel comfortable with, because they have been in schools, families, governments, are all set up on the basis of retributive justice, the idea that there are certain things you must do, and if you don't you deserve to suffer, and if you do things defined as right by authorities, then you deserve to be rewarded."""

key8 = """anytime we get people to do things out of fear that we're going to punish them if they don't, or out of shame or guilt. It's very obvious then that whatever we got that person to do is costly. Because we are then experienced as a source of violence. Somebody who is prepared to make them suffer if they don't do what we want."""

[NVCTraining.intro.Q13]

key1 = """At his trial for war crimes in Jerusalem, Eichmann was asked was it difficult for you to send thousands of people to their death?

Eichmann on answered very honestly, he said to tell you the truth. It was easy. Our language made it easy. 

...my fellow Nazi officers and I came up with a name for describing the language of its we were taught in schools to us and especially to us in our position as officers in the military. We called this language Amtssprache up between us."""

key2 = """Asked for examples of Amtssprache, Eichmann said it's a language in which you deny responsibility for your actions. If you don't feel responsible for your actions, you don't feel so bad when you do things like send people to their death."""

key3 = """If somebody asked you why you do it, you say I had to, I had no choice. if people question that and say, Well, what do you mean you had no choice then you say, superiors orders, company policy. It's the law."""

key4 = """Nonviolent communication is designed to help us remain conscious of choice every moment to believe that every action we take, we choose to take. 

We don't necessarily like some actions that we take, but we don't do anything we don't choose to do."""

key5 = "Words like have to, should, ought, must, can't, are dangerous, as I would define danger, because they turn out people who don't feel responsible for their actions."

key6 = "Nonviolent communication is a language that heightens our consciousness that we have choice. Every moment of our lives, we have choice. Nobody can make us do anything."

[NVCTraining.intro.Q14]
key1 = "Nonviolent communication is a more natural way of being. It simply says, Let's stay connected to life, the life within us. Like any other form of life, whether it be a tree or animals, life requires being connected enough to live to know how to fulfill our needs. So in that sense, nonviolent communication is a very simple process."

key2 = "The reason that it's so difficult is that it requires liberating ourselves from centuries of education that have buried what's alive in us behind cultural education that is designed to make us nice Dead people, not compassionate living people."