title = "Marshall Rosenberg Quotes - NVC Training 9 - Gratitude"

[NVCTraining.gratitude.Q01]
key1 = "This process Nonviolent Communication has great power to enrich our lives, when it is our intention to create the connections necessary for compassionate giving to take place."

[NVCTraining.gratitude.Q02]
key1 = "It's a process that helps us to share that information with others, how to be honest and share what's alive in us in a way that enables others to enjoy compassionately giving to us."

[NVCTraining.gratitude.Q03]
key1 = "A very important component in keeping this consciousness alive is the process of expressing gratitude to one another in a way that can be trusted that it's a celebration of life, and not a form of communication that's designed to manipulate us to do things that others want."

[NVCTraining.gratitude.Q04]
key1 = "I mean that we let people know how our needs have been fulfilled, and how our life has been enriched by something they have done. Our only intention is to celebrate that, and not in any way to put them under pressure to continue doing that which we would like them to do."

[NVCTraining.gratitude.Q05]
key1 = '''Gratitude in NVC

- We tell them what they have done, that has enriched our life. (Observation)
- We express how it has, by letting them know the need of ours that was fulfilled by the action (Needs)
- How we feel as a result of that need being fulfilled. (Feelings)'''

[NVCTraining.gratitude.Q06]
key1 = "When we express gratitude, we use the same ingredients of clear observation, expressions of feelings and needs."

key2 = "Now we're talking about actions that have contributed to our well being and needs that have been fulfilled, and the pleasureful things that follow these needs having been fulfilled."

[NVCTraining.gratitude.Q07]
key1 = "Nonviolent Communication is clear on observations, feelings, and needs."

[NVCTraining.gratitude.Q08]
key1 = "it's extremely important that we build into our lives, opportunities to exchange sincere gratitude, that we have opportunities to express it to others and to receive it."

[NVCTraining.gratitude.Q09]
key1 = "Every time we receive sincere gratitude, it helps us to remember how good it feels to contribute to the well being of human beings. How good it feels to contribute to our own well being, to the well being of others, how good it feels to celebrate that."

[NVCTraining.gratitude.Q10]
key1 = '''When we express gratitude in a Nonviolent Communication way:

- make it clear to the other person what they did that enriched your life
- how you feel right now, when you think about that
- and what need of yours was fulfilled.'''

[NVCTraining.gratitude.Q11]
key1 = '''It has been my experience that there is nothing more fulfilling for human beings than when they exercise this power to enrich life and get confirmation that they have done so they can really experience how their efforts have enriched other people's lives.'''

[NVCTraining.gratitude.Q12]
key1 = '''What can feel better than using this power we have to enrich life, in the service of life, and seeing how our efforts have made life more wonderful for people?'''

[NVCTraining.gratitude.Q13]
key1 = '''Our ability to express gratitude well, is highly correlated with how well we're able to express our pain, and receive empathy for our pain, and transform the pain.'''

[NVCTraining.gratitude.Q14]
key1 = '''what gratitude might I have within me that I haven't expressed yet, that I would hate not to express?'''

[NVCTraining.gratitude.Q15]
key1 = '''One day a man named Jesus came around to my grandmother’s door. He asked for a little food, she gave him more.

He said he was Jesus the Lord; she didn’t check him out with Rome. He stayed for several years, as did many without a home.'''

[NVCTraining.gratitude.Q16]
key1 = '''I went to the people that I didn't express my gratitude to, because I assumed that they knew it, and I asked them, Did you know?

And half of them did and half of them didn't.

But even the ones who did still told me they would have liked to have heard it.'''

[NVCTraining.gratitude.Q17]
key1 = '''It's not only important to express gratitude, it's also very important to receive it well.'''

[NVCTraining.gratitude.Q18]
key1 = '''Just as it's hard for us to express gratitude, if we have this thinking of obligation, duty, and that's why you do things and that's all that's necessary.'''

key2 = '''That means we often don't express gratitude, thinking it's the other person's duty and obligation, they shouldn't need any gratitude for it.'''

[NVCTraining.gratitude.Q19]
key1 = "it is our light, not our darkness, that scares us the most."
key1-link = "https://en.wikiquote.org/wiki/Marianne_Williamson#A_Return_to_Love:_Reflections_on_the_Principles_of_%22A_Course_in_Miracles%22_(1992)"

[NVCTraining.gratitude.Q20]
key1 = "When we have been living under a domination culture, where we are rewarded and punished by authorities told to do things out of duty and obligation, it's hard within that structure to really feel that we are created out of divine energy."

[NVCTraining.gratitude.Q21]
key1 = "I know you can't give me me, no matter what you do. All I ever want from you, is you."
key1-author = "Ruth Bebermeyer"

[NVCTraining.gratitude.Q22]
key1 = "I want to be sure that gratitude that I have for others is expressed, and I want to make sure that gratitude others expressed to me is received."

[NVCTraining.gratitude.Q23]
key1 = "My wife and I take time every morning before we go off into the world to stop and express openly what the other has done that has enriched our life, and to tell them as best we can, how it enriched our lives."

[NVCTraining.gratitude.Q24]
key1 = "We found that when we take that much time to stop and slow down and celebrate what's being done, how it's enriching our lives, we find that even then when we get into the hard stuff, it is so much more productive."

