title = '''Marshall Rosenberg Quotes - NVC Training 6 - Authority: Respect vs Fear'''

[NVCTraining.authority.Q01]
key1 = '''Nonviolent communication suggest that we get certain things clear when we're in a position of authority, or when we're dealing with people in positions of authority

One of these is the difference between respect for authority and fear of authority. Getting these mixed up creates a great deal of pain for people.'''

key2 = '''Respect for authority, as I use the term, is manifest when we know things that people don't know, or can do things that they don't know how to do. 

They see that these things are very valuable and they see that these things are being offered to them and not imposed upon them, then they would have what I call respect for authority.'''

key3 = '''Fear of authority ... is usually built into the structure of either the family, the school, the business, the government.

This structure gives us the right to impose things on people, that we can reward or punish, to get people to do what we want.'''

key4 = '''Respect for authority needs to be earned. We need to clearly communicate with people so they can see the value of what we're offering.'''

[NVCTraining.authority.Q02]
key1 = '''Obedience is maintained when people submit, because we have the power to either reward or punish. 

Willing cooperation only can be received when people feel free from this kind of coercion. And they trust that their needs as human beings are valued.'''

[NVCTraining.authority.Q03]
key1 = '''When we're in positions of authority, we want people to do things because they choose to do it, because they see how it will enrich their lives and the lives of others to do it. That requires a radically different exercise of authority than many of us know how to do.'''

[NVCTraining.authority.Q04]
key1 = '''To use punishment and reward to get people to do things is very costly for the organization and for the relationships of people within the organization.'''

[NVCTraining.authority.Q05]
key1 = '''I used to try to figure out what can I do so that the students will see me as a human being offering them something that's valuable to me, that I hope will be valuable to them. How can we create that quality of connection?'''

[NVCTraining.authority.Q06]
key1 = '''when we are in this position of authority called parent, if we don't watch out, we allow our cultural training to lead us to treat this person we label as our child in a way that's far less respectful and caring than people we would label as our neighbors.'''

key2 = '''I would hope that we would show the quality of honesty where we revealed our own feelings and needs and request, not criticism and demands. Whether this person is three or 53'''

[NVCTraining.authority.Q07]
key1 = '''When we are in these positions labeled authority, within families, within schools, within the business place, it's very easy, if we don't watch out, to lose connection with our own humaneness and the humaneness of others, and see people as titles.'''

[NVCTraining.authority.Q08]
key1 = '''if we don't watch out, we give the institution the power to turn us into something other than what we are as a human being, we become the label'''

key2 = '''If we don't watch out, we give away our power to institutions to make monsters out of us. 

https://www.simplypsychology.org/milgram.htm
'''

key3 = '''very Often the institutions that we might be within might not be set up to maintain the kind of values that we hold within ourselves.'''

key4 = '''It's extremely important that we learn how not to give away our power to authority. That no matter how people might make demands of us when they are in possitions of authority, we hear it as a request and never as a demand. We don't give our power away to the authority to tell us what we are, we hear their humaneness behind their message.'''

[NVCTraining.authority.Q09]
key4 = '''One of the things that I find very important to prepare our children with is to show them how to maintain their own integrity, their own value system, even if they are going to be in structures that have different values than they have.''' 

[NVCTraining.authority.Q10]
key1 = '''when I was a child, I had been educated to believe that teachers know what's right, and so within the school setting, I was giving away power to the authority. That wasn't good for me.'''

[NVCTraining.authority.Q11]
key1 = '''I believe everyone has a right to dance and sing even if they move and sound like a crow with a crippled wing.'''

[NVCTraining.authority.Q12]
key1 = '''It's important that we not be obedient to authority, that we always recognize our choice. It's also important to recognize that rebellion is only halfway to being fully free. If we're rebelling against authority, we're still recognizing its power over us.'''

[NVCTraining.authority.Q13]
key1 = '''I like that cartoon to remind myself that no matter what structure I'm in, they may control the environment, but they can't control me. I'm free within any structure, to choose what I want to do, and why I want to do it.'''

[NVCTraining.authority.Q14]
key1 = '''I would hope that we help ourselves and others develop is a consciousness, no matter what the structure, that we not give away our values and succumb to what the structure tells us to do.'''

[NVCTraining.authority.Q15]
key1 = '''When we are in a position of authority, it is not the objective to control people. It is to offer people what we have to offer, from my position of authority, but not to impose it.'''

[NVCTraining.authority.Q16]
key1 = '''Carl Rogers said, I have the belief that the most important part of learning is to wonder, what's worth learning'''

key2 = '''I would like us all to do some wondering and on the basis of this wondering, take actions that free us from authority and institutions that function in ways that are not conducive to our living the lives we choose to live.'''

key3 = '''I'd like us to wonder whether we have fully developed our ability to stay human, even when we're in the institutions that make it a challenge to stay human.'''

key4 = '''I'd like us to wonder whether we have learned to express our humanity, even when we are labeled in a way as superior or inferior.'''

key5 = '''I hope we are wondering whether we've fully developed our ability to see the humaneness of people in positions of authority, who aren't able to stay connected to their humaneness and who speak a language of domination and who use punitive tactics.'''

key6 = '''I'd like us to wonder whether we have fully developed our ability to see that person's humaneness, and that we can communicate with them and show them other ways of getting all needs met, beside the ways that we have been trained to use power within domination systems.'''

[NVCTraining.authority.Q17]
key1 = '''I'd like us all to learn how to use power with people, not power over people.'''