title = '''Marshall Rosenberg Quotes - NVC Training 4 - Dynamics of Empathy'''

[NVCTraining.dynamics-of-empathy.Q01]
key1 = '''Imagine yourself getting up on a surfboard, this requires getting in touch with a certain energy. If you don't get on exactly, you can get knocked off. To me, empathy is somewhat like that.

Empathy is getting in touch with the life energy that's coming through another person.'''

key2 = '''When people need empathy the most, they're often expressing it in a pretty violent way. In that sense, it's very much like surfboard riding. How to get in touch with this energy and flow with it? The energy coming through people is, for me, a very beautiful divine energy. When I can really stay connected with it, I feel like I'm riding in a very precious flow of energy.'''

[NVCTraining.dynamics-of-empathy.Q02]
key1 = '''See me Beautiful, look for the best in me. That's what I really am, and all I want to be It may take some time, it may be hard to find, but see me beautiful.

See me beautiful, each and every day. Could you take a chance, could you find a way, to see me shining through every thing I do and see me beautiful.'''

[NVCTraining.dynamics-of-empathy.Q03]
key1 = '''The most important part of empathy is the hardest.

It involves our presence, our full presence to what is alive in this person, at this moment.'''

[NVCTraining.dynamics-of-empathy.Q04]
key1 = '''Martin Buber the Israeli philosopher and psychotherapist says that presence is the most powerful gift one person can give to another. 

A powerful gift and a precious gift. When we give this gift to others, this gift of our presence, it is a major component of healing.'''

key2 = '''If we start to think about what the person is saying, we lose this presence. All of the theories that we might bring into the present moment, about this person, will get in the way of our staying empathically connected.'''

key3 = '''At university, we're trained to analyze people what leads them to behave as they do. 

That kind of intellectual training and analysis of what goes on historically that creates present problems, that can get in the way of empathy.'''

key4 = '''One of the things that we need to stay clear about, is not to get mixed up intellectual understanding with empathy.'''


[NVCTraining.dynamics-of-empathy.Q05]

key1 = '''Another frequent misunderstanding of empathy is to confuse it with sympathy'''

key2 = '''If a person starts to talk about some pain they're having, the other person might say, "I'm so sad that you're going through this suffering." 

That sadness and caring on the part of this person could probably be well received if the person in pain first received empathy.'''

key3 = '''When we are giving a sympathetic response, we're talking about ourselves. This takes the focus away from what is alive in the other person.'''

key4 = '''I have found that people can enjoy that sympathetic response too, once they have had the empathic connection that they need. But to confuse these two things can be very painful.'''

key5 = '''How do you tell somebody that when you tell me "how sad you are", and start to give me advice, I know you mean well, but it's not only not what I need, it actually stimulates more pain, it leaves me feeling more lonely with that pain.

We don't want to mix up empathy and sympathy.'''

key6 = '''Another thing we don't want to mix up is giving advice with empathy.

Very often we think that we are showing understanding of people and we jump right in and start to give them advice.'''

[NVCTraining.dynamics-of-empathy.Q06]
key1 = '''In nonviolent communication as we'll see, we never say I understand.

We do something far more powerful. We demonstrate understanding.'''

[NVCTraining.dynamics-of-empathy.Q07]
key2 = '''Empathy takes place in the now. If the other person is telling me about some things that happened to their life in the past that caused great pain in them, I put my focus on what is alive in them now when they're telling me this.'''

[NVCTraining.dynamics-of-empathy.Q08]
key1 = '''Empathy involves:

- presence
- focus on the now
- focus on feelings and needs.

That means not on thoughts. Most people are used to talking about their thoughts.'''

key2 = '''many of the thoughts that people make, especially those that judge others or themselves, are really tragic expressions of what they're feeling and needing at that moment.'''

key3 = '''When we are making empathic connections, if somebody tells us what they think about us, we don't hear that.

We try never to hear what a person thinks about us.
I really believe that if we learn how to hear the life behind these thoughts, will enjoy people more and live longer.'''

key4 = '''We go to the feelings and needs being distorted by the thoughts that criticize oneself or others. To do that will require some guessing, some sensing, of what the feelings and needs might be. Because the speaker is not directly saying, this means we'll be wrong some of the time.'''

[NVCTraining.dynamics-of-empathy.Q09]
key1 = '''We need to put into words, what we sense the person might be feeling. and then we connect their feeling to what they might be needing.

This means that we don't get addicted to being right.

We want to connect, It's not a test that we have to get right.'''

[NVCTraining.dynamics-of-empathy.Q10]
key1 = '''In nonviolent communication, we never try to be perfect. We try to be progressively less stupid.

We're conscious that anything that's worth doing is worth doing poorly.'''

[NVCTraining.dynamics-of-empathy.Q11]
key1 = '''If somebody says they're upset about something and say, "You had no right to do what I'm upset about," and what if we didn't do what they said?

It's very tempting to want to jump in and correct the person and give them the facts.'''

key2 = '''When people are upset, even if they're being upset is stimulated by a misinterpretation on their part, it really helps if we can empathically connect, before correction.'''

[NVCTraining.dynamics-of-empathy.Q12]

key1 = '''I was trained to try to help people connect the present problems they're having with things that happened earlier in their life to get them insights into this. 

The people usually found this very interesting and helpful in a certain way. 

It took me quite a few years to realize how much more powerful it was for me to empathically connect with them, rather than to intellectually analyze how their problems began'''

[NVCTraining.dynamics-of-empathy.Q13]
key1 = '''When people trust that you value what's alive in them what they're feeling and needing at a given moment, that takes more precedence for you, than whether what they're saying is right or wrong. This has a big impact on the relationship. It makes compassionate connecting much easier when people really feel that what's alive in them is what matters to you.'''

key2 = '''when we empathically connect with a message that comes at us. It gets the person in touch with even more pain that they're experiencing. When we stay connected to that, they go even deeper.''' 

key3 = '''Very often people need us to stay with them for a while, because if we stay with their present feelings and needs, that gets them in touch with other deeper feelings and needs that are also going on within them. Sometimes this can take quite a while before the person really feels fully understood. 

A very important part of empathically connecting is to make sure we stay with the empathic connection, until the other person feels fully understood.'''

[NVCTraining.dynamics-of-empathy.Q14]

key1 = '''When a person receives empathy from another, not only does the person who receives it feel good, but it's highly likely that anyone observing this feels good. There is something very special when somebody in pain receives an empathic connection from someone.'''

key2 = '''In our nonviolent communication training, we show people how to hear the human behind the no. To be conscious that, if we hear a no, we're hearing very little about what's really alive in this person at this moment. 

We need to do the same thing with the no as we do if somebody is telling us what's wrong with us, to hear through the message to what is alive and the person when they say this.'''

key3 = '''many of the parents that I work with, 'no' is one of the messages that they find hardest to deal with in their children. 

They say, Marshall, what can I do? I tell my son, it's time for him to go to bed, and he says, No, I don't want to go. 

I suggest to hear what is the person feeling and needing when they say that. We'll learn a lot about what's going on by doing that. We'll show the person we are more interested in the connection with them than in their immediately responding to our request. That is a very powerful message when people trust that the connection is valued over their submission to whatever we are requesting.'''

[NVCTraining.dynamics-of-empathy.Q15]
key1 = '''To interrupt them when you have heard more words than you want to hear, and when the words are not really connecting you clearly to what is alive in the person. 

Always say, "Excuse me" and then what we say is to bring the conversation back to life, back to what is alive in this person at this moment, behind all the words.'''

key2 = '''...then the person goes on to tell us this long story about what happened with their father. 

Here's where I might interrupt, but I would interrupt to try to connect to what's alive and then now, behind all these words. 

I might say excuse me, excuse me for interrupting but I really want to be sure I'm connecting to what you want me to hear by telling me this. Are you saying that you feel angry right now even when you think about how your father used to communicate with you, and you'd really like some understanding of how painful that was?'''

key3 = '''For many of the people who come to our nonviolent communication trainings, what I'm suggesting, focusing our attention on the present, on what's alive in the other person, what they're feeling and needing. They tell me it's a rhythm they're not used to.

They're so used to getting defensive when other people tell them what's wrong with them.'''


[NVCTraining.dynamics-of-empathy.Q16]
key1 = '''I was keeping a lot of myself hidden, because I was telling myself that I had to be afraid of what people might say to me. But then I started to realize I don't have to worry about what people say to me. I only have to worry about how I respond to that.'''

[NVCTraining.dynamics-of-empathy.Q17]
key1 = '''I listed some of the things that I was most afraid of what people might say to me, if I was honest.

I could see that I was afraid to reveal things about myself, for fear of getting that message back. For every one of them, I thought, "What might the stimulus be for the person to say that to me?"'''

key2 = '''For each item on the list then that I saw that I had been hiding parts of myself out of fear of somebody might saying this back to me. For every one of the messages, I practice sensing guessing what that person might be feeling and needing, if they said that to me.'''

key3 = '''these things that I had been so afraid other people might say, how different it was, if I could just learn to hear the feelings and needs behind any message.'''

key4 = '''I don't have to worry about being honest with people and how they might respond. I only have to be prepared to empathically connect with whatever comes back. That means my power is in my hands. My security is in my hands. It's not in what other people think about me or say to me.'''

[NVCTraining.dynamics-of-empathy.Q18]
key1 = '''Words are windows or they're walls
They sentence us or set us free 
When I speak and when I hear
Let the love light shine through me

http://ryanrowe.com/reflections/words-are-windows-ruth-bebermeyer/'''

