title = "Marshall Rosenberg Quotes - NVC Training 8 - Social Change"

[NVCTraining.social-change.Q01]
key1 = '''some gangs call themselves gangs, street gangs. I'm not so worried about these gangs and the damage that they might be doing.'''

key2 = '''Gangs that I'm worried about, some of them call themselves governments, some call themselves corporations ... organizations of people that have a big impact over our lives, and are doing some things that I think contribute to great violence on the planet and great suffering.'''

key3 = '''how can each of us develop our own power, become conscious of our power and use it to transform these organizations so that they serve life rather than threaten life?'''

key4 = '''This can be quite a challenge because the spirituality, language, and means of influence that these gangs perpetuate, make it very hard for us to become conscious of our power and to use it.'''

key5 = '''The organizations that are doing the most damage on our planet can be quite a task for us to think of how, we as individuals, can change them. We are often overwhelmed just with our own personal lives, and trying to get our needs of our family met.'''

key6 = '''The organizations that are doing the most damage on our planet can be quite a task for us to think of how, we as individuals, can change them. We are often overwhelmed just with our own personal lives, and trying to get our needs of our family met.'''

[NVCTraining.social-change.Q02]
key1 = "Nonviolent Communication helps us to differentiate between objectives which are to undo the damage created by the systems, but to recognize how different that is than changing the systems, that create the problem."

key2 = "Do we want to just heal the people hurt by these structures? Or do we want to radically transform the structures?"

key3 = "we can use Nonviolent Communication to go upstream and to connect with the people who are creating and supporting the structures that do the violence, and use Nonviolent Communication to show them other ways of serving other than those which are oppressing people."

[NVCTraining.social-change.Q03]
key1 = "One way that Nonviolent Communication support us, is to help us to look inside and see how do I want to meet this important need of mine, to serve life?"

key2 = "we can use our Nonviolent Communication, consciousness and skills to conduct With the people creating the damage and positively compassionately influencing them to transform the structure so that they serve life for all rather than oppress people."

[NVCTraining.social-change.Q04]
key1 = "social change involves the transformation of consciousness, people seeing other ways of doing things that they choose to do."

[NVCTraining.social-change.Q05]
key1 = "if we want to bring about social change nonviolently, we want the change to occur because a critical mass of people willingly shift what they're doing, from one position to another."

[NVCTraining.social-change.Q06]
key1 = "to be very clear very quickly, about what we want, so as to stimulate a dialogue in which the other side can find out what they need to know to determine whether they want to support us or not."

[NVCTraining.social-change.Q07]
key1 = "whether we use force with our children, or with organizations, we want to be sure that it's the protective use of force and not the punitive use of force."

key2 = '''when we use the protective use of force, we don't see the other person as evil or bad and deserving of punishment. Our focus is on how we can stop what is creating the damage without being violent in the process'''

key3 = "Our thinking is focused on how we would like to protect life."

[NVCTraining.social-change.Q08]

key1 = "we met and looked at what actions could we take that would protect the children and help us create the connection with those who are doing the damage, so that we could have a dialogue with them, and come out with a way that would meet everybody's needs."

key2 =  "I showed them that I thought it would be more effective if we created signs that purely communicated our needs and our intent, but in no way implied that we saw the people at the school as evil or bad."

[NVCTraining.social-change.Q09]
key1 = '''as defined by Joanna Macy, despair work helps us to deal with the pain that we're feeling as a result of what is happening, out of our feeling of powerlessness to do anything about it.'''

key1-link = "http://www.personaltransformation.com/joanna_macy.html"

key2 = """Transformative Spirituality is when we are energized by our consciousness of how life can be better served in another way. We come out with joy and pleasure at the image of how it can be, rather than motivated by anger and bitterness toward people creating structures that harm"""

key2-link = "http://www.kenwilber.com/Writings/PDF/ASpiritualitythatTransforms_GENERAL_b42000.pdf"

[NVCTraining.social-change.Q10]
key1 = '''We need a spirituality that not only helps us to transcend our bitterness and our anger, but integrated with a real consciousness of what is happening that's creating the violence.'''

key2 = "That mobilizes us to create change, not just to hope that by purifying ourselves the energy coming from us will create the change."

[NVCTraining.social-change.Q11]
key1 = '''One of my social change objectives for the last several years has been to do what I can do to contribute to transforming our judicial system from one based on the concept of retributive justice to one based on restorative justice.'''

key2 = "Our present judicial system, retributive justice, comes out of a spirituality I'm very concerned about, that I feel does great violence on our planet."

key3 = "I'm talking about the kind of spirituality, that is based on the concept that there are superiors who know what is right, and who on the basis of their judgments have the right to punish or reward people."


[NVCTraining.social-change.Q12]
key1 = "Our judicial system is based on this way of thinking that there are people who know what's right and what's wrong, and who therefore have the right to punish people when they deserve it."

key2 = "The concept that I'm interested in supporting is restorative justice, which is based on an entirely different way of thinking and leads to entirely different ways of exercising justice."

[NVCTraining.social-change.Q13]
key1 = "Restorative justice has as its purpose, to find ways of getting everyone's needs met so that peace and harmony can be retrieved when pain and conflict exists between parties."


[NVCTraining.social-change.Q14]
key1 = '''There's three parties that have to be dealt with whenever somebody needs have not been met, through a crime of some sort.

There's the person who's been affected by the crime. We want to end in a way that this person is brought back to healing and in which their needs are fulfilled.

A second party in this kind of justice is the person who acted in a way that created pain for others.

We want to restore the situation by replacing whatever education led to this person behaving as they did is now replaced with an education that supports their contributing to people's well being, rather than doing things which create suffering for people.

The third party involved in restorative justice is the community that provided the education that contributed to the person's crime.

We need to look at why is it that some people get their needs met by robbing, raping, and doing other things that cause great suffering.

The old spirituality says this is because such people are evil and deserving to be punished and suffer for their actions.

The spirituality of restorative justice says that these people are meeting their needs in the way they have been educated to meet their needs.'''

key2 = "We want to restore the situation by replacing whatever education led to this person behaving as they did is now replaced with an education that supports their contributing to people's well being, rather than doing things which create suffering for people."

key3 = '''We need to look at why some people get their needs met by robbing, raping, and doing other things that cause great suffering.

The old spirituality says this is because such people are evil and deserve to be punished and suffer.

The spirituality of restorative justice says these people are meeting their needs in the way they have been educated to meet their needs.'''

key4 = '''How have we failed in this situation and what do we need to do to support this person learning a different way, and to look at how we are educating people, and to make sure we are educating people to see that our well being is one of the same that we can never meet our own needs at other people's expense.'''

[NVCTraining.social-change.Q15]
key1 = '''There are many cultures throughout the world that have historically always use restorative justice and still do.

Anthropologist Margaret Mead, Ruth Benedict, Ashley Montagu, have studied these cultures and describe how different is their spirituality and how different is their way of dealing with people who act in a way that creates pain and disharmony.'''

key2 = '''what restorative justice looks like in these cultures that go about seeing justice in a radically different way, whose spirituality does not believe that people are evil, or good. It believes that we all, when we're functioning in harmony with our nature, enjoy more than anything else, contributing to one another's well being.'''

[NVCTraining.social-change.Q16]
key1 = "what we need to do, to restore peace and harmony is reconnect people with what they need to be conscious of, that will help them naturally enjoy contributing to people's well being, rather than to act in ways that are harmful to people."

